### ISSUE TITLE
Changing focal point may break images

### ISSUE THREAD

**Issue by joso9001** [coderedcorp/wagtail-cache#16] opened 2019-10-07 14:24 UTC
Changing focal point may in some cases break images until the Wagtail Cache is cleared.

Versions:
- Django 2.2.5
- Linux 4.19
- Python 3.7.4
- Wagtail 2.6.2
- Wagtail Cache 0.5.2

Steps to reproduce:
- Start a fresh instance of the Django development server.
- Edit the focal point of an image for a page where it actually matters.
- View the live page containing the Wagtail user bar in a logged in session.
- Repeat these steps _a couple of times_.
  - Open the page in a _new_ private browser instance.
  - _Force refresh_ (Ctrl+R) the page in the private browser.
  - Close the private browser instance.
  - Force refresh the page in the logged in browser instance.

I have managed to reproduce this issue both in Chromium and Firefox. Note that I have only tested this on the development server. Clearing the cache manually resolves this issue. If this is a real problem, then perhaps the cache should be cleared whenever an image's focal point changes?

**Comment by vsalvino** [comment] 2019-10-07 18:21
Thanks for the detailed report. This is the "intended" behavior because it is up to the developer to decide when to clear the cache, the cache will never automatically clear. We do have some docs on how to automatically trigger a cache clear though - so you can probably quite easily implement what you need via wagtail hooks:

See: https://docs.coderedcorp.com/wagtail-cache/stable/getting_started/usage.html

**Comment by JockeTF** [comment] 2019-10-08 09:02
Thanks, that's good to know!

I noticed it happens sometimes even after I cleared the cache. I've even seen it happen without even editing an image. So, maybe it doesn't have anything to do with editing them, despite it making this happen a bit more likely?

[Video demonstrating the issue.](https://youtu.be/WM8kVpq5mZI)

I can't really explain why it happens without further investigation, but disabling the cache does make the "issue" go away. Feel free to close this issue if you believe this is the way it should be though!

**Comment by vsalvino** [comment] 2019-10-08 16:28
Whenever you change the focal point of an image, wagtail re-generates the rendition. This is essentially the same effect as uploading a new image. However it leaves the old rendition there, those never get deleted by wagtail.

Wagtail cache caches the html page that references the image, and tells the browser to also cache that page until further notice. So if you change the image, which is now at a different URL, the cached html page is still pointing to the old URL, which is why you're seeing the old image until clearing the cache. On top of that, the browser has also cached the html page itself, and will not retrieve a new one until the life of the cache has expired or a HEAD of the page tells the browser that a new version is available.

These are classic problems that always have, and always will, come along with caches. 

You can further debug by inspecting the http headers in your browser. Open the developer tools (F12). Go to the network tab. Then make a request to the page. Look at the headers of the http response. You should see X-WagtailI-cache which will tell you if we are serving a cached page (hit) or a non-cached page (miss). Or if the page is not capable (skip). You should also look at the Cache-Control header which tells the browser if it should cache this page and for how long in seconds.

**Comment by vsalvino** [comment] 2021-03-04 19:24
Closing this as it follows normal caching behavior and is not a bug in and of itself.

**Closed by vsalvino** 2021-03-04 19:24 UTC
